# Generated by Django 4.2.29 on 2026-03-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="policies.policy",
            ),
        ),
    ]
