# Generated by Django 4.2.29 on 2026-03-04 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "license_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("Hospital", "Hospital"),
                            ("Clinic", "Clinic"),
                            ("Pharmacy", "Pharmacy"),
                            ("Laboratory", "Laboratory"),
                            ("Specialist", "Specialist Center"),
                        ],
                        default="Hospital",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["name"],
            },
        ),
    ]
