# Generated by Django 4.2.29 on 2026-03-09 00:00

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("providers", "0001_initial"),
        ("apps.users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderFeedback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_score",
                    models.PositiveSmallIntegerField(
                        validators=[MinValueValidator(1), MaxValueValidator(5)]
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="feedback_entries",
                        to="providers.provider",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="provider_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        related_name="+",
                        on_delete=models.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Feedback",
                "verbose_name_plural": "Provider Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
