# Generated by Django 4.2.29 on 2026-03-04 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic Coverage"),
                            ("Standard", "Standard Coverage"),
                            ("Premium", "Premium Coverage"),
                            ("Comprehensive", "Comprehensive Coverage"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "max_coverage_amount",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=12
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "ordering": ["-created_at"],
            },
        ),
    ]
