# Generated by Django 4.2.29 on 2026-03-04 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="citizen",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Citizen"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
